# Generated by Django 6.0.2 on 2026-02-19 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_promoted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='review',
            name='promotion_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
