# Generated by Django 6.0.2 on 2026-02-19 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='is_promoted',
        ),
        migrations.RemoveField(
            model_name='review',
            name='promotion_expires',
        ),
        migrations.AddField(
            model_name='product',
            name='is_promoted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='promotion_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
