# Generated by Django 6.0.2 on 2026-02-19 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_promotionrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotionrequest',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='promotionrequest',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
